apiVersion: v1
kind: Service
metadata:
  name: nginx-service-nodeport
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80 # service port to connect to application
      targetPort: 80 # application port to connect with the application
      nodePort: 30433 # port to connect to in node
  selector:
    app: nginx
